### ISSUE TITLE
[SUBTASK of Story #143] Create an Avatar Component

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#151]
### 🚀 Summary:

Create a avatar icon so users can login, logout, and view their profile/setting.

### 📜 Description:

- [ ] Add default fallback profile picture
- [x] Display Initials when logged in
- [x] Add appropriate buttons (profile, settings, login, logout)

**Comment by briantkatch** [comment]
I think the initials are fine for now, saves an image upload feature. 

But we probably want to replace the question mark when not signed in with a nice icon.

**Comment by briantkatch** [comment]
@annabelzecchel or @JeremyCrete are you available to handle the default picture fallback / change it to something other than a question mark? or @CarciDev do we backlog this issue for sprint 1 and remove it from the auth story as it is only marginally relevant?

**Comment by annabelzecchel** [comment]
> @annabelzecchel or @JeremyCrete are you available to handle the default picture fallback / change it to something other than a question mark? or @CarciDev do we backlog this issue for sprint 1 and remove it from the auth story as it is only marginally relevant?

@briantkatch Yes I can take a look, unless @CarciDev you think its better to backlog this one.

**Comment by CarciDev** [comment]
> > @annabelzecchel or @JeremyCrete are you available to handle the default picture fallback / change it to something other than a question mark? or @CarciDev do we backlog this issue for sprint 1 and remove it from the auth story as it is only marginally relevant?
> 
> 
> 
> @briantkatch Yes I can take a look, unless @CarciDev you think its better to backlog this one.

Honestly given that the feature is already functional, front end will just create what a default image will look like, back end will route default profile pictures to new accounts. Do we even have an issue that handles if we wanted to update the avatar? Possibly maybe an attribute within CRUD.

**Comment by briantkatch** [comment]
@CarciDev I think the intention for now is simply to replace the question mark with a generic person icon or something. A changeable avatar would be a possible unique feature for a future sprint. If we think we will implement the change of all avatar, maybe we just go ahead and close this issue.

**Comment by CarciDev** [comment]
You're right. Since the functionality is implemented, then in the scope of the issue and the story, it has been satisfied. You can close it.
