### ISSUE TITLE
[USER STORY] Implement a Promotions Page

### ISSUE THREAD

**Issue by annabelzecchel** [NathanGrenier/SOEN-341#237]
### 🚀 Story Summary:

As a user, I want to easily navigate to the promotions page and play the wheel of fortune. 
The wheel of fortune shall have 8 options for the user to select. If the user's choice matches what the wheel has landed on, then the user is awarded with a promotions code, which can be applied at checkout. 
The promotions page shall clearly indicate the instructions to play, as well as the benefits of playing the wheel. 

### 📋 Tasks:

- [ ] {Draft task}

### 📝 Acceptance Criteria:

- [ ] Promotions Page is accessible from the footer.
- [ ] Promotions Page is accessible from a button on the Home Page.
- [ ] Promotions Page contains instructions on how to play the wheel.
- [ ] Promotions Page contains a button to trigger the drawer-pop up.
- [ ] The drawer pop-up contains the wheel, the message box, and the buttons for the user to select one our of the 8 options.
- [ ] Promotions Page and the drawer pop-up is engaging for the user.
