### ISSUE TITLE
Complete the Project tab's Readme

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#52]
### 🚀 Story Summary:

Flesh out the project's readme with information on how to use the project space.

### 📋 Tasks:

- [ ] Create a diagram representing the issue hierarchy
- [ ] Explain the issue tag sync workflow
- [ ] Explain the metadata to add to issues (size, priority, iteration)
- [x] Provide a rundown on the different views in the project
- [x] Document the time that corresponds to 1 estimate unit. (Should be 1hour per 1 estimate point)
- [x] Mention the project's insight section

**Comment by briantkatch** [comment]
@NathanGrenier not sure if this issue might be already completed

**Comment by NathanGrenier** [comment]
> @NathanGrenier not sure if this issue might be already completed

It isn't. Not sure if the prof will even care if it's done though. I'll change it to low priority for now.

**Comment by NathanGrenier** [comment]
Didn't complete all of the tasks, but enough were completed to meet sprint 1's evaluation criteria.
