### ISSUE TITLE
Setup Git Flow Workflow

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#54]
### 🚀 Story Summary:

[Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) is the workflow paradigm that this project will use. Currently, Gitflow is being used instead. 

### 📋 Tasks:

- [x] Create Develop Branch
- [x] Configure Environment Secrets for Develop and Production (Preview might need changes)
- [x] #55
- [x] Add branch protections to develop (and update main)
- [x] Add wiki page describing the workflow

### 📝 Additional Context:

As of now, there isn't an automated develop environment to stage the changes made in feature branches before creating a new deployment (merging into main).

**Comment by briantkatch** [comment]
Link to Git Flow is a 404; I assume it's the same as the Atlassian link I gave?

**Comment by NathanGrenier** [comment]
> Link to Git Flow is a 404; I assume it's the same as the Atlassian link I gave?

It was a different one. I changed it to the Atlassian link.
