### ISSUE TITLE
[USER STORY] Frontend: UI/UX

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#83]
### 🚀 Story Summary:

Develop a responsive and intuitive frontend user interface for a car rental web application. The interface should cater to a wide range of users, providing a seamless experience from browsing available cars to completing a rental transaction. 

### Core Features:
>As a **Customer**, I want **to be informed and navigate through the website** so that **I find the vehicle that suits my needs**. 
>As a **System Administrator**, I want **to perform CRUD operations on a simple UI** so that **searching and booking a vehicle with our company is a quick and easy process**. 
>As a **Customer Service Representative**, I want **the ability to search for and check in/out customer vehicles quickly** so that **the customers are satisfied with our availability of vehicles and quality of service**. 

### 📋 Tasks:

- [ ] https://github.com/NathanGrenier/SOEN-341/issues/44#issue-2065238138
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/91
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/66
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/92
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/99
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/93
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/95
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/75
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/96
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/97
- [ ] https://github.com/NathanGrenier/SOEN-341/issues/98
