### ISSUE TITLE
[SUBTASK of Story #75] Implement reservation cancellation functionality

### ISSUE THREAD

**Issue by briantkatch** [NathanGrenier/SOEN-341#86]
On the reservation details page described above, a link to modify or cancel the reservation will be present.

Upon clicking the Cancel reservation link, a secondary confirmation will appear on screen. Upon confirming their intention, the cancelled property will be set on the reservation in the database, an email will be sent to the user confirming the cancellation, and they will be returned to their dashboard.

- [ ] Cancel link appears on the reservation details page
- [ ] Log in required to cancel; customers other than the holder cannot cancel a user's reservation
- [ ] Cancelling changes the status of the reservation to cancelled in the database, leaving a tombstone of the reservation.
