### ISSUE TITLE
[SUBTASK of Story #75] Implement reservation creation/modification functionality

### ISSUE THREAD

**Issue by briantkatch** [NathanGrenier/SOEN-341#87]
### Creating a reservation

On the user's dashboard, the user will first be prompted to set their pick up and return date and time. They can then see available vehicles (which are not already reserved or overdue), and filter them down by properties such as number of seats. Each vehicle will be shown with its daily price. Finally, they will be shown a confirmation screen with a total price, and once confirmed, a new reservation will be inserted into the database. The reservation will appear on the user's dashboard and an email confirmation will be sent to the user.

### Modifying a reservation

Upon clicking the Modify reservation link, they will go through a flow similar to the original booking process (for development efficiency, these processes should ideally be driven by the same code). They will be presented with an option to set the pick-up and return time, which will be pre-filled with the pick-up and return time already set for the reservation. They will be allowed to choose an available vehicle at any branch, or continue with their current vehicle if it is available for the entire new timeframe.  The price of the modified reservation will be quoted based on the then-current price of the car. Upon confirming the modification, a new reservation will be inserted into the database with a pointer to the previous reservation. The previous reservation's status therefore becomes replaced and is no longer considered for inventory purposes, however, the history of changes to the reservation is available for consultation by the user. A confirmation email is sent to the user including the new reservation price and details.

### Acceptance Criteria

Optional equipment/accessories have been left out of this issue for Sprint 1.

- [ ] Reservations can be created from the dashboard (a transition to a new page is acceptable
- [ ] Reservations can only be made from available inventory
- [ ] Upon making a reservation, the user receives a confirmation.
- [ ] When modifying a reservation, a user has 'first dibs' on the car that is currently reserved for them, if they wish to keep it and it is available for the new booking time.
- [ ] When modifying a reservation, the price is re-quoted.
- [ ] When modifying a reservation, it replaces the old reservation in the database, leaving a tombstone of the old reservation.
- [ ] When modifying a reservation, the user receives a confirmation.
- [ ] A customer's reservation can't be modified by another customer.
